name: Infra Provisioning through Terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (eg., dev, staging, prod)"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - staging
        - prod
  
  pull_request:
    branches:
      - main
      
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::664418994073:role/eks-github-role
          aws-region: ap-south-1
          id-token: true

      - name: Terraform Init
        run: | 
          cd Infra
          terraform init

      - name: Terraform Destroy
        run: |
          cd Infra
          terraform destroy -auto-approve -var-file=../Infra/env/dev/terraform.tfvars
